@FreakyFashion_backend_HostAddress = https://localhost:5000

GET {{FreakyFashion_backend_HostAddress}}/api/product
Accept: application/json

### BY ID

GET {{FreakyFashion_backend_HostAddress}}/api/product/4
Accept: application/json

### BY SEARCH

GET {{FreakyFashion_backend_HostAddress}}/api/product?slug=t-shirt
Accept: application/json

### CREATE
Post {{FreakyFashion_backend_HostAddress}}/api/product
Content-Type: application/json


{
  "name": "green T-Shirt",
  "description": "A classic green t-shirt.",
  "price": 199,
  "image": "/images/green-t-shirt.png",
  "categories": [1]
}

### DELETE

DELETE {{FreakyFashion_backend_HostAddress}}/api/product/3


### ------------  CATEGORY

GET {{FreakyFashion_backend_HostAddress}}/api/category
Accept: application/json

### BY ID

GET {{FreakyFashion_backend_HostAddress}}/api/category/5
Accept: application/json

### BY SEARCH

GET {{FreakyFashion_backend_HostAddress}}/api/category?slug=t-shirts
Accept: application/json

### CREATE
Post {{FreakyFashion_backend_HostAddress}}/api/category
Content-Type: application/json

{
  "name": "sun dresses",
  "image": "/images/sun-dress.png"
}

### DELETE

DELETE {{FreakyFashion_backend_HostAddress}}/api/category/3
