namespace FreakyFashion_backend.DTOs.Categories
{
    public class CreateCategoryDto
    {
        public string Name { get; set; } = null!;
        public string Image { get; set; } = null!;
    }
}

//slug is generated by the backend here too